bot/core.py, bot/extensions/stats.py
Displays a summary of a user's solved challenge categories:
```
+++++----- CRYPTO x1
++++++++++ WEB x2
---------- MISC x0
+++++----- PWN x1
---------- REVERSE x0
---------- STEGO x0
```
=> Add `!stats me` command

bot/extensions/ctf.py, bot/help_info.py
Adds `!ctf leave` command
Closes #20
=> Added ctf leave

README.md, bot/db_models.py, bot/extensions/ctf.py, bot/help_info.py, bot/helpers.py
=> #39 - fixed solve cmd+ formatting fixes

bot/core.py, bot/db_models.py
=> Reacting on edited commands

bot/exceptions.py, bot/extensions/ctf.py, bot/help_info.py
A new command `!ctf rmchall <chall_name>` has been added for deleting challenges
=> Added challenge delete cmd 

README.md, bot/db_models.py, bot/extensions/ctf.py, bot/help_info.py, bot/helpers.py
Changes:
A notebook is created with each new challenge.
New command: `!ctf notes` to display notebook url
Closes #44
=> Added notes support

README.md, bot/db_models.py, bot/extensions/ctf.py, bot/help_info.py
This allows `!ctf setcreds` to take an optional link for login. i.e. `!ctf setcreds Kokos Password http://ctflink.com`
=> Added link to setcreds command

README.md, bot/core.py, bot/help_info.py, bot/helpers.py, docker-compose.yml
Adds `!wolfram <question>` command
Closes #48
=> Wolfram api integration

README.md, bot/core.py, bot/db_models.py, bot/extensions/ctf.py, bot/help_info.py
A ctf command to remind  the members with a message before the start of the CTF
=> Reminder feuture

README.md, bot/core.py, bot/db_models.py, bot/extensions/ctf.py, bot/help_info.py
Reverts apogiatzis/KyriosZolo#52
=> Revert "Reminder feuture"

README.md, bot/core.py, bot/db_models.py, bot/extensions/ctf.py, bot/help_info.py
=> reminder for CTFs

README.md, bot/core.py, bot/db_models.py, bot/exceptions.py, bot/extensions/ctf.py, bot/help_info.py
Reminder functionality has been implemented.
New command: `!ctf setreminder [<date>]`
Closes 43
=> Set reminder functionality

docker-compose.yml
=> Added restart policy

.circleci/config.yml, Dockerfile, docker-compose-with-reloading.yml, docker-compose.yml
=> AWS migration + some other issues

.circleci/config.yml, ovisbot/bot.py, ovisbot/cog_manager.py, ovisbot/commands/base.py, ovisbot/commands/manage.py, ovisbot/commands/rank.py, ovisbot/config.py, ovisbot/db_models.py, ovisbot/extensions/hackthebox/hackthebox.py, ovisbot/helpers.py, requirements.txt
=> HTB async + extensions fix

README.md, ovisbot/cog_manager.py, ovisbot/exceptions.py, ovisbot/extensions/cryptohack/cryptohack.py, ovisbot/extensions/ctf/ctf.py, ovisbot/extensions/hackthebox/hackthebox.py, ovisbot/helpers.py, ovisbot/todo-fixes.md
ctf.py:
+ Extended "!ctf countdown" command to also show time left until the end
of CTF
+ Bug fix on L117
+ Fix on L759
exceptions.py:
+ Added MissingEndTimeException
todo-fixes.md:
+ Added possible fixes / recommendations
=> Enhancement: Extend "!ctf countdown" command

ovisbot/cog_manager.py, ovisbot/extensions/cryptohack/cryptohack.py, ovisbot/extensions/hackthebox/hackthebox.py, ovisbot/extensions/utils/utils.py, ovisbot/helpers.py
Issue: https://github.com/cybermouflons/ovisbot/issues/98
utils.py:
+ Added command "!utils rotn"
=> Enhancement: Added functionality for Caesar cipher

.github/workflows/codeql-analysis.yml
Enables GitHub's CodeQL scanning.
=> feat(tools): enable CodeQL scanning

ovisbot/exceptions.py, ovisbot/extensions/ctf/ctf.py
=> feat(ctf): add optional difficulty argument on addchallenge

ovisbot/extensions/ctftime/ctftime.py, ovisbot/extensions/ctftime/ctftime_helpers.py
1. Naive fix of HTML parsing bug
2. Use of `chunkify`
=> 2021-03-16 => naive fix of parsing bug

ovisbot/extensions/ctf/ctf.py
Added Hardware as challenge category.
=> Added hardware category

CONTRIBUTE.md
Ran into some `Couldn't launch bot. Not configured properly` errors.
Realized I was missing some env vars and had to add them **and** do a `docker-compose up --build` for the new `.env` file to be picked up.
=> docs: update CONTRIBUTE.md
